# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Holmies' do
	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '8.1'
	pod 'GoogleMaps'
end

target 'HolmiesTests' do

end

